#! /bin/bash
#
# Example panel for LemonBoy's bar

. $HOME/.dotfiles/system/panel_colors

num_mon=$(bspc query -M | wc -l)
PADDING="  "

while read -r line ; do
    case $line in
	D*)
	    # date output
	    date="%{A1:$HOME/.dotfiles/system/calender-popup:}$PADDING${line#?}$PADDING%{A}"
	    ;;
	C*)
	    # clock output
	    clock="$PADDING${line#?}$PADDING"
	    ;;

	B*)
	    # battery percent output
	    battery="$PADDING${line#?}$PADDING"
	    ;;
	T*)
	    # xtitle output
	    title="${line#?}$PADDING$PADDING"
	    ;;

	V*)
	    # alsa volume
	    volume="%{A1:dvol -t:}$PADDING${line#?}$PADDING%{A}"
	    ;;
	L*)
	    # wifi link
	    wifi="$PADDING${line#?}$PADDING"
	    ;;
	P*)
	    # power
	    power="%{A1:$HOME/.dotfiles/system/shutdown-popup:}$PADDING${line#?}$PADDING%{A}"
	    ;;

	W*)
	    # bspwm internal state
	    wm_infos=""
	    IFS=':'
	    set -- ${line#?}
	    while [ $# -gt 0 ] ; do
		item=$1
		name=${item#?}
		case $item in
		    M*)
			# active monitor
			if [ $num_mon -gt 1 ] ; then
			    wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG}$PADDING${name}$PADDING%{B-}%{F-}  "
			fi
			;;
		    m*)
			# inactive monitor
			if [ $num_mon -gt 1 ] ; then
			    wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG}$PADDING${name}$PADDING%{B-}%{F-}  "
			fi
			;;
		    O*)
			# focused occupied desktop
			wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u}$PADDING${name}$PADDING%{-u}%{B-}%{F-}"
			;;
		    F*)
			# focused free desktop
			wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}%{+u}$PADDING${name}$PADDING%{-u}%{B-}%{F-}"
			;;
		    U*)
			# focused urgent desktop
			wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u}$PADDING${name}$PADDING%{-u}%{B-}%{F-}"
			;;
		    o*)
			# occupied desktop
			wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG}%{A:bspc desktop -f ${name}:}$PADDING${name}$PADDING%{A}%{B-}%{F-}"
			;;
		    f*)
			# free desktop
			wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}%{A:bspc desktop -f ${name}:}$PADDING${name}$PADDING%{A}%{B-}%{F-}"
			;;
		    u*)
			# urgent desktop
			wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG}$PADDING${name}$PADDING%{B-}%{F-}"
			;;
		esac
		shift
	    done
	    ;;
    esac
    more_mons=""
    for i in `seq 1 $num_mon`; do
        more_mons="$more_mons%{S+}%{l}${wm_infos}"
    done
        
    printf "%s\n" "%{S0}${wm_infos}${music}%{r}${title}${wifi}${volume}${battery}${date}${clock}${power}$more_mons"
done
