---
- name: Set up zsh for user
  become: no
  vars:
    the_user: "{{ ansible_user_id }}"
  block:
    - name: change user shell to zsh
      become: yes
      user:
        name: "{{ the_user }}"
        shell: /usr/bin/zsh
