#+TITLE:Dotfiles
#+AUTHOR:Philipp Uhl

* dotfiles



** Topical

Everything's built around topic areas. If you're adding a new area to your
forked dotfiles — say, "Java" — you can simply add a `java` directory and put
files in there. Anything with an extension of `.zsh` will get automatically
included into your shell. Anything with an extension of `.symlink` will get
symlinked without extension into `$HOME` when you run `script/bootstrap`.

** What's inside



** Components

There's a few special files in the hierarchy.

- =bin/= :: Anything in `bin/` will get added to your `$PATH` and be made
  available everywhere.
- =topic/*.zsh= :: Any files ending in `.zsh` get loaded into your
  environment.
- =topic/path.zsh= :: Any file named `path.zsh` is loaded first and is
  expected to setup `$PATH` or similar.
- =topic/completion.zsh= :: Any file named `completion.zsh` is loaded
  last and is expected to setup autocomplete.
- =topic/*.symlink= :: Any files ending in `*.symlink` get symlinked into
  your `$HOME`. This is so you can keep all of those versioned in your dotfiles
  but still keep those autoloaded files in your home directory. These get
  symlinked in when you run `script/bootstrap`.
- =topic/(*).(*).dotconfig= :: Any file with name \1 is symlinked to .config/\2

** Install

Run this:

#+BEGIN_SRC sh
git clone https://github.com/phuhl/.dotfiles.git ~/.dotfiles
cd ~/.dotfiles
./script/bootstrap
sudo ./script/install
sudo chsh <username> /bin/zsh
#reboot
#+END_SRC

This will symlink the appropriate files in `.dotfiles` to your home directory.
Everything is configured and tweaked within `~/.dotfiles`.

** Thanks

I forked [[https://github.com/holman][Zach Holman]]s [[https://github.com/holman/dotfiles][dotfiles]] who forked [[http://github.com/ryanb][Ryan Bates]]' [[http://github.com/ryanb/dotfiles][dotfiles]]. Because i restructured my fork to an extend it made sens to put it all into its own repository.
