- name: Install River?
  when: window_manager == "river"
  block:
    - name: Create directories for template files
      ansible.builtin.file:
        path: "{{ ansible_env.HOME}}/{{ item.path }}"
        state: directory
      with_community.general.filetree: "{{ role_path }}/templates/"
      when: item.state == 'directory'

    - name: Create symlinks for template files
      ansible.builtin.file:
        src: "{{ item.src }}"
        path: "{{ ansible_env.HOME}}/{{ item.path }}"
        state: link
        follow: false #         avoid corrupting target files if the link already exists
      with_community.general.filetree: "{{ role_path }}/templates/"
      when: item.state == 'file'

    - name: Hide GTK Window Decorations
      ansible.builtin.include_role:
        name: gtk3-window-decorations
      vars:
        present: true

    - name: Install wayland
      ansible.builtin.include_role:
        name: wayland
    - name: Install River packages
      ansible.builtin.include_role:
        name: packages
      vars:
        packages:
          - state: present
            names:
              - brightnessctl # Control brightness from CLI
              - swaylock #      Lock screen
              - swayidle #      Deamon to handle screen timeout
              - gammastep
              - xdg-desktop-portal # Service for screen sharing
              - xdg-desktop-portal-wlr # Wl roots backend for # xdg-desktop-portal
              - slurp #         Used for screen sharing geometry stuff
              - grim #          CLI tool for taking screenshots on wayland
              - swaybg #        Background images
          - state: removed
            names:
              - rofi
          - state: present
            aur: true
            names:
              - river #         The WM
              - way-displays #  Configure monitor setup
              - wlopm #         Output manger (turn screens on/off)
              - rofi-lbonn-wayland-git
              - satty #         Screenshot tool like flameshot that
                #               actually works on river
              # - rofi-lbonn-wayland # rofi-lbonn-wayland-git while the other one does not work
    - name: Enable and start service for screen sharing
      ansible.builtin.systemd:
        name: xdg-desktop-portal
        scope: user
        enabled: yes
        state: started
