- name: Install bspwm?
  when: window_manager == "bspwm"
  block:
    - name: Create directories
      ansible.builtin.file:
        path: "{{ ansible_env.HOME}}/{{ item.path }}"
        state: directory
      with_community.general.filetree: "{{ role_path }}/templates/"
      when: item.state == 'directory'

    - name: Create symlinks
      ansible.builtin.file:
        src: "{{ item.src }}"
        path: "{{ ansible_env.HOME}}/{{ item.path }}"
        state: link
        follow: false #         avoid corrupting target files if the link already exists
      with_community.general.filetree: "{{ role_path }}/templates/"
      when: item.state == 'file'
    - name: Install X11
      ansible.builtin.include_role:
        name: x11
    - name: Install Bspwm packages
      ansible.builtin.include_role:
        name: packages
      vars:
        packages:
          - state: present
            names:
              - rofi
              - plank
              - pantheon-files # Elementary file manager
              - file-roller # Gnome archive manager
              - numlockx
              - dmenu
              - nitrogen # Background images
              - stalonetray

          - aur: true
            state: present
            names:
              - picom-git
              - i3lock-color
              - nerd-fonts-complete
