- name: Enable pacman parallel downloading
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: "^#?ParallelDownloads = "
    line: "ParallelDownloads = 7"
    insertafter: "^\\[options\\]"
- name: Update Repositories
  become: yes
  pacman:
    update_cache: yes
    upgrade: no
- name: Update keyring
  become: yes
  pacman:
    state: latest
    name:
      - archlinux-keyring
- name: Upgrade system
  become: yes
  pacman:
    upgrade: yes
- name: Install Repo packages
  become: yes
  pacman:
    state: "{{item.state}}"
    name: "{{item.names}}"
  loop: "{{packages}}"
  when: '"aur" not in item'
- name: Setup Yay
  block:
    - name: Create `aur_builder` user
      become: yes
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel
    - name: Allow `aur_builder` user to run `sudo pacman` without a password
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        create: yes
        validate: "visudo -cf %s"
    - name: Install yay
      become: yes
      become_user: aur_builder
      aur:
        state: present
        use: makepkg
        name: yay
- name: Install AUR packages
  become: yes
  become_user: aur_builder
  aur:
    use: yay
    state: "{{item.state}}"
    name: "{{item.names}}"
  loop: "{{packages}}"
  when:
    - "'aur' in item"
    - item.aur == true
- name: Enable services
  become: yes
  ansible.builtin.systemd:
    name: bluetooth
    enabled: yes
    state: started
