- name: Create directories
  ansible.builtin.file:
    path: "{{ ansible_env.HOME}}/{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  with_community.general.filetree: "{{ role_path }}/templates/"
  when: item.state == 'directory'

- name: Create symlinks
  ansible.builtin.file:
    src: "{{ item.src }}"
    path: "{{ ansible_env.HOME}}/.config/{{ item.path }}"
    state: link
    follow: false # avoid corrupting target files if the link already exists
    mode: "{{ item.mode }}"
  with_community.general.filetree: "{{ role_path }}/templates/.config"
  when: item.state == 'file'

- name: Create ssh config file
  ansible.builtin.copy:
    force: false
    src: "{{ role_path }}/templates/.ssh/config"
    dest: "{{ ansible_env.HOME}}/.ssh/config"
    mode: "0600"

- name: Enable and start service
  ansible.builtin.systemd:
    name: ssh-agent
    scope: user
    enabled: yes
    state: started
