# Make sure to include in this list only tools that are agnostic to
# the display server (i.e. wayland/x server). All tools that require
# specific versions for each display server have to be installed in
# that specific role. For now.

# (Better would be, if they where all here and conditionally
# chosen. In the future maybe.)

packages:
  - state: present
    names:
      # Build basics
      - base-devel

      # Services
      - xf86-input-synaptics
      - bluez # Bluetooth deamon
      - bluez-utils
      - libnotify

      # Audio drivers
      # https://wiki.archlinux.org/title/PipeWire
      - pipewire
      - pipewire-alsa
      - wireplumber
      - pipewire-pulse

      # Fonts
      - ttf-freefont
      - ttf-dejavu
      - ttf-roboto-mono
      - ttf-roboto
      - adobe-source-han-sans-cn-fonts
      - adobe-source-han-sans-jp-fonts
      - adobe-source-han-sans-kr-fonts
      - adobe-source-han-sans-otc-fonts
      - adobe-source-han-sans-tw-fonts

      # CLI Tools
      - p7zip
      - zip
      - python-pip
      - jq
      - man-db
      - git
      - htop
      - screen
      - alsa-utils
      - zsh
      - acpi
      - playerctl # Multi media controls
      - pamixer # Pulse audio mixer
      - hunspell
      - hunspell-de
      - hunspell-en_us
      - nano

      # Desktop tools
      - flameshot
      - evince
      - tumbler # Thumbnail service via D-Bus
      - firefox
      - viewnior
      - torbrowser-launcher
      - pavucontrol # Audio interface GUI tool
      - keepassxc

      # Configuration tools
      - v4l-utils # Webcam setup tool

      # File systems
      - exfat-utils
      - ntfs-3g

      # Codecs
      - x264

  - state: present
    aur: true
    names:
      - kpcli
      - volta-bin
      - nerd-fonts-complete
