#!/bin/sh

# dbus-update-activation-environment --systemd DISPLAY
dbus-update-activation-environment --systemd DISPLAY XAUTHORITY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river

systemctl --user import-environment DISPLAY XAUTHORITY WAYLAND_DISPLAY
hash dbus-update-activation-environment 2>/dev/null && \
     dbus-update-activation-environment --systemd DISPLAY XAUTHORITY WAYLAND_DISPLAY




# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Spwan some programs
riverctl map normal Super Return spawn alacritty
riverctl map normal Super+Shift Return spawn emacs
riverctl map normal Super q spawn firefox
riverctl map normal Super Space spawn launcher
riverctl map normal None Print spawn screenshot

# Super+Q to close the focused view
riverctl map normal Super+Shift Q close

# Super+Shift+E to exit river
riverctl map normal Super+Shift Escape exit

# Super+l to lock the screen
riverctl map normal Super l spawn "waylock lock"

# Super+z to show notifications
riverctl map normal Super z spawn toggleNotificationCenter


# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super Period focus-view next
riverctl map normal Super Comma focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift Period swap next
riverctl map normal Super+Shift Comma swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super+Control Period focus-output right
riverctl map normal Super+Control Comma focus-output left

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift+Control Period send-to-output right
riverctl map normal Super+Shift+Control Comma send-to-output left

# Super+Return to bump the focused view to the top of the layout stack
#riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super I send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift I send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt h move left 100
riverctl map normal Super+Alt n move down 100
riverctl map normal Super+Alt e move up 100
riverctl map normal Super+Alt i move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control h snap left
riverctl map normal Super+Alt+Control n snap down
riverctl map normal Super+Alt+Control e snap up
riverctl map normal Super+Alt+Control i snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift h resize horizontal -100
riverctl map normal Super+Alt+Shift n resize vertical 100
riverctl map normal Super+Alt+Shift e resize vertical -100
riverctl map normal Super+Alt+Shift i resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super s toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    riverctl map $mode None XF86AudioRaiseVolume  spawn 'volume inc'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'volume dec'
    riverctl map $mode None XF86AudioMute         spawn 'volume mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightness inc'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightness dec'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0xff0000
riverctl border-color-unfocused 0x333333

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Use lswt -j
# Make certain views start floating
# riverctl float-filter-add app-id float
# riverctl float-filter-add title "popup title with spaces"
riverctl float-filter-add title "Ediff"
riverctl float-filter-add app-id "flameshot"
riverctl float-filter-add title "Firefox — Sharing Indicator"
riverctl float-filter-add app-id "file-roller"
riverctl float-filter-add title "KeePassXC - Browser Access Request"
riverctl float-filter-add title "KeePassXC -  Access Request"
riverctl float-filter-add title "OpenRCT2"
riverctl float-filter-add app-id "TeamViewer"

# Set app-ids and titles of views which should use client side decorations
# riverctl csd-filter-add app-id "gedit"

# Mouse options
riverctl focus-follows-cursor normal
riverctl hide-cursor timeout 5000 # milliseconds
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp on-focus-change

riverctl input pointer-1267-12753-VEN_04F3:00_04F3:31D1_Touchpad drag enabled
riverctl input pointer-1267-12753-VEN_04F3:00_04F3:31D1_Touchpad middle-emulation enabled
riverctl input pointer-1267-12753-VEN_04F3:00_04F3:31D1_Touchpad tap enabled
riverctl input pointer-1267-12753-VEN_04F3:00_04F3:31D1_Touchpad tap-button-map left-right-middle

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

# Display layout manager
way-displays > /tmp/way-displays.${XDG_VTNR}.${USER}.log 2>&1 &

# Background img
swww init &
sleep 3 && swww img ~/images/downloads/wallpapers/19513k34grf1ejpg.jpg &

# Lock screen when idle
# If annoying, maybe install and look into: sway-audio-idle-inhibit
swayidle -w &


waybar &
gammastep &
deadd-notification-center &
