wayland_packages:
  - state: present
    names:
      - wl-clipboard
  - state: absent
    names:
      - emacs
      - vlc
  - state: present
    aur: true
    names:
      # Wayland version of tools
      - emacs29-git
      - vlc-git

      # Wayland specific
      - alacritty
