- name: Create directories
  ansible.builtin.file:
    path: "{{ ansible_env.HOME}}/{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  with_community.general.filetree: "{{ templatesdir }}/link"
  when: item.state == 'directory'
- name: Create directories
  ansible.builtin.file:
    path: "{{ ansible_env.HOME}}/{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  with_community.general.filetree: "{{ templatesdir }}/copy"
  when: item.state == 'directory'
- name: Create directories for Root
  ansible.builtin.file:
    path: "/root/{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  with_community.general.filetree: "{{ templatesdir }}/root"
  when: item.state == 'directory'
  become: true

- name: Create symlinks
  ansible.builtin.file:
    src: "{{ item.src }}"
    path: "{{ ansible_env.HOME}}/{{ item.path }}"
    state: link
    follow: false # avoid corrupting target files if the link already exists
    mode: "{{ item.mode }}"
  with_community.general.filetree: "{{ templatesdir }}/link"
  when: item.state == 'file'

- name: Copy templated configs
  template:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME}}/{{ item.path }}"
    mode: "{{ item.mode }}"
  with_community.general.filetree: "{{ templatesdir }}/copy"
  when: item.state == 'file'

- name: Copy templated configs for root
  template:
    src: "{{ item.src }}"
    dest: "/root/{{ item.path }}"
    mode: "{{ item.mode }}"
  with_community.general.filetree: "{{ templatesdir }}/root"
  when: item.state == 'file'
  become: true
- name: Print the gateway for each host when defined
  ansible.builtin.debug:
    msg: "{{ templatesdir }}"
