- name: Install packages
  ansible.builtin.include_role:
    name: packages
  vars:
    packages:
      - state: present
        names:
          - sudo

- name: Ensure sudo includes sub config files
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "@includedir /etc/sudoers.d"
    validate: "visudo -cf %s"
- name: Ensure sudo can do everything
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "%wheel ALL=(ALL:ALL) ALL"
    validate: "visudo -cf %s"





