#! /bin/zsh

. $HOME/.dotfiles/system/panel_colors

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=18
PANEL_FONT_FAMILY="CamingoCode:size=9"
#PANEL_FONT_FAMILY="Cantarell:size=9"
#PANEL_FONT_FAMILY="Cantarell:size=9"
ICON_FONT="FontAwesome:size=9"
ICON_FONT2="fontcustom:size=9"
# export PANEL_FIFO PANEL_HEIGHT PANEL_FONT_FAMILY

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc subscribe > "$PANEL_FIFO" &


# clock
while true;
	do 
		echo 'C\uf017' $(date '+%H:%M');
	sleep 5;
done > "$PANEL_FIFO" &

# date
while true;
do echo 'D\uf073' $(date +'%b %d')
	sleep 5
done > $PANEL_FIFO &
# battery
while true;
do
ON_LINE=$(acpi -a | grep on-line)
BATT_LEVEL=$(acpi -b | grep -o '[[:digit:]]\+%' | sed 's/%//')
if [ "$BATT_LEVEL" -ne "" ] ; then
    BATT_LEVEL="$BATT_LEVEL %"
fi
if [ -n "$ON_LINE" ]
then
    BATT_LEVEL="\uf0e7 $BATT_LEVEL"
else
    if [ $BATT_LEVEL -ge 80 ]
    then
	BATT_LEVEL='\uf240' $BATT_LEVEL
    else
        if [ $BATT_LEVEL -ge 60 ]
        then
	    BATT_LEVEL='\uf243' $BATT_LEVEL
        else
            if [ $BATT_LEVEL -gt 40 ]
            then
	        BATT_LEVEL='\uf242' $BATT_LEVEL
            else
                if [ $BATT_LEVEL -gt 20 ]
                then
                    BATT_LEVEL='\uf243' $BATT_LEVEL
                else
	            BATT_LEVEL='%{T3}\uf244%{T1}' $BATT_LEVEL
                fi
            fi
        fi
    fi
fi
echo "B$BATT_LEVEL"

	sleep 30;
done > "$PANEL_FIFO" &

# alsa volume
while true;
do
ALSA_VOLUME=$(amixer -M get Master | tail -1 | grep -o '...%' | sed 's/\[//' | sed 's/%//' | sed 's/ //')
ALSA_STATE=$(amixer get Master | tail -1 | grep -o '\[on]')

if [ $ALSA_STATE ]
then
	if [ $ALSA_VOLUME -ge 70 ]
	then
		echo V'\uf028' $ALSA_VOLUME
	fi
	if [ $ALSA_VOLUME -gt 0 -a $ALSA_VOLUME -lt 70 ]
	then
		echo V'\uf027' $ALSA_VOLUME
	fi
	if [ $ALSA_VOLUME -eq 0 ]
	then
		echo V'\uf026' $ALSA_VOLUME
	fi
	else
		echo V'\uf026' $ALSA_VOLUME
	fi
	sleep 0.1
done > $PANEL_FIFO &


# wifi
while true;
do
WIFI_SSID=$(iwconfig |  grep 'ESSID:"[^"]*"' -o | sed 's/ESSID:"\([^"]*\)"/\1/')
	echo L'\uf1eb' $WIFI_SSID 
	sleep 10
done > $PANEL_FIFO &

# power 
echo P'\uf011' > $PANEL_FIFO &


cat "$PANEL_FIFO" | $HOME/.dotfiles/system/panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -f "$ICON_FONT" -f "$ICON_FONT2" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" -u 2 -a 20 | zsh &

wait

