---
- name: Install Aur Packages
  hosts: all
  tasks:
    - name: Install
      become: yes
      aur:
        use: yay
        state: present
        name:
          - picom-ibhagwan-git
          - keeweb-desktop-bin
          - i3lock-color
          - kpcli
          - volta-bin
          - nerd-fonts-complete
