---
- name: "Set up your system"
  hosts: all
  roles:
    # Base setup:
    - zsh
    - autologin
    - backlight
    - packages
    - git
    - dotfiles
    - rslsync
    - ssh

    # Window managers. Choose in inventory/host_vars/localhost/vars.yml
    - kde
    - river
    - bspwm

    # Implicitly called, should not be needed explicitly, just here
    # for completion or when I want to run this role manually.
    # - wayland
    # - x11
