#!/bin/bash

export XAUTHORITY=/home/philipp/.Xauthority
if [ "$(/usr/bin/id -u)" != "1000" ] ; then
    /usr/bin/sudo -u philipp XAUTHORITY=/home/philipp/.Xauthority DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus /usr/bin/notify-send.py "$@"
else
    export DISPLAY=:0
    export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
    /usr/bin/notify-send.py "$@"
fi
