#!/bin/bash

if [ "$(id -u)" != "1000" ] ; then
    sudo -u philipp DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send.py "$@"
else
    export DISPLAY=:0
    export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
    notify-send.py "$@"
fi

