#!/bin/bash

get_service() {
    systemctl --type=service --plain | grep openvpn-client@nordvpn | awk '{print $1}'
}

service=$(get_service)
test -z "$service" && exit_msg 1 "No openvpn connection exist."
systemctl restart $service


config=$(echo "$service" | tr @. " " | awk '{print $ 2}')

ip_should=$(cat /etc/openvpn/client/${config}.conf | head -4 | tail -1 | awk '{print $2}')

# requires pacman -S bind-tools
test -z $(whereis dig | awk '{print $2}') && echo "dig not installed, run 'pacman -S bind-tools'" 


sleep 0.3

for i in {1..100}
do
    if [ "$ip_is" = "$ip_should" ]; then
        echo -e "\nok"
        vpnStatus
        exit
    else
        echo -n "."
        sleep 0.1
        ip_is=$(dig +short myip.opendns.com @resolver1.opendns.com)
    fi
done

echo "not ok, $ip_is != $ip_should"
vpnStatus
sleep 0.1
allUserNotifySend "VPN not connected" "IP check failed: $ip_is != $ip_should" --app-name="nordVPN" -u critical --replaces-process="vpnNotifications"
exit 1

