#!/bin/bash

get_service() {
    systemctl --type=service --plain | grep openvpn-client@nordvpn | awk '{print $1}'
}

service=$(get_service)
test -z "$service" || systemctl stop $service

systemctl restart iptables.service

vpnStatus

